# Generated by Django 4.1.7 on 2023-03-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waste_reg',
            old_name='city',
            new_name='pincode',
        ),
    ]
