# Generated by Django 4.1.7 on 2023-03-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='waste_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compowner', models.CharField(max_length=200)),
                ('compid', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=500)),
                ('typeofbussiness', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
    ]
