# Generated by Django 4.1.7 on 2023-03-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='waste_reg',
        ),
    ]
