# Generated by Django 4.1.7 on 2023-03-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0002_delete_waste_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='waste_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=500)),
                ('Address', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
    ]
