# Generated by Django 4.1.7 on 2023-03-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='waste_reg',
            new_name='employee_reg',
        ),
    ]
