# Generated by Django 4.1.7 on 2023-03-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='survey_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=500)),
                ('Gender', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=20)),
                ('Qualification', models.CharField(max_length=500)),
                ('Experience', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
    ]
