# Generated by Django 4.1.4 on 2023-04-19 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_addimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addimg',
            name='message',
        ),
    ]
