# Generated by Django 4.1.4 on 2023-04-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_addimg_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='addimg',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
