# Generated by Django 4.1.4 on 2023-04-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_addimg_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='addimg',
            name='trash',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
