# Generated by Django 4.1.5 on 2023-04-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_addimg_trash'),
    ]

    operations = [
        migrations.AddField(
            model_name='addimg',
            name='employee',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
