# Generated by Django 4.1.5 on 2023-04-20 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_addimg_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='addimg',
            name='payment',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='addimg',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.survey_reg'),
        ),
    ]
