# Generated by Django 4.1.5 on 2023-04-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_addimg_payment_addimg_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='addimg',
            name='predict',
            field=models.BooleanField(default=False),
        ),
    ]
